CITE_L001_prelim_white_list.out : prelim_whitelist.txt
        perl ../match_cite_data_to_existing_barcodes.pl ../C70_Caudate_5pr_10XBarcode_S19_L001_R1_001.fastq ../C70_Caudate_5pr_10XBarcode_S19_L001_R2_001.fastq $< > $@


CITE_L002_prelim_white_list.out : prelim_whitelist.txt
        perl ../match_cite_data_to_existing_barcodes.pl ../C70_Caudate_5pr_10XBarcode_S19_L002_R1_001.fastq ../C70_Caudate_5pr_10XBarcode_S19_L002_R2_001.fastq $< > $@
